### ISSUE TITLE
Follow tail

### ISSUE THREAD

**Issue by zee276** [apptastic-software/fix-log-viewer#1]
This viewer is great. An extra option to Follow the tail would be great addition.

**Comment by w3stling** [comment]
It is possible in [release 1.2.0](https://github.com/apptastic-software/fix-log-viewer/releases/tag/v1.2.0)

In live log view you can choose to run a shell command or an program that writes FIX messages to standard out. FIX log viewer will detect any FIX message that is printed to standard out and display them in real-time.

For example to tail a local FIX log file enter `tail -f <path to log file>` in the shell command text box.

Or to tail a FIX log file on a remote machine enter `ssh -T user@machine 'tail -f <path to log file on remote machine> | cat -v'` in the shell command text box. Before running that in FIX log viewer you need to run `ssh-add <path private ssh key>` from a shell to prevent it from asking for password.
